[package]
name = "hoc-log"
version = "0.1.0"
authors = ["Hampus Lidin <hampuslidin@gmail.com>"]
edition = "2021"

[dependencies]
console = "0.11"
dialoguer = "0.10"
lazy_static = "1.4.0"
thiserror = "1.0.29"
