[package]
name = "homepi-hosting-tools"
version = "0.1.0"
authors = ["Hampus Lidin <hampuslidin@gmail.com>"]
edition = "2018"

[[bin]]
name = "h2t"
path = "./src/main.rs"

[dependencies]
anyhow = "1.0"
console = "0.11"
dialoguer = "0.6"
futures = "0.3"
git2 = "0.13"
heck = "0.3"
indexmap = "1.6.0"
lazy_static = "1.4"
nom = "5.1"
num_enum = "0.5"
plist = "1.0"
rand = "0.7"
reqwest = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
shiplift = { git = "https://github.com/softprops/shiplift.git", branch = "master" }
ssh2 = "0.8"
structopt = "0.3"
strum = "0.19"
strum_macros = "0.19"
tempfile = "3.1"
tokio = { version = "0.2", features = ["macros"] }
url = "2.1.1"
xz2 = { version = "0.1", features = ["tokio"] }
zip = "0.5"
