[package]
name = "homepi-hosting-tools"
version = "0.1.0"
authors = ["Hampus Lidin <hampuslidin@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
console = "0.11"
dialoguer = "0.6"
git2 = "0.13"
lazy_static = "1.4"
log = "0.4"
nom = "5.1"
pretty_env_logger = "0.4"
reqwest = { version = "0.10", features = ["blocking"] }
shiplift = "0.6"
structopt = "0.3"
tempfile = "3.1"
tokio = "0.1"
