[package]
name = "hoc-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
heck = "0.4.0"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.36"
quote = "1.0.15"
rand = "0.8.5"
syn = { version = "1.0.86", features = ["visit-mut"] }
