fqdn: {hostname}
prefer_fqdn_over_hostname: true
manage_etc_hosts: true

package_update: true
package_upgrade: false

users:
  - name: {admin_username}
    groups:
      - adm
      - dialout
      - cdrom
      - sudo
      - audio
      - video
      - plugdev
      - games
      - users
      - input
      - netdev
      - gpio
      - i2c
      - spi
    ssh_authorized_keys:
      - {ssh_pub_key}
    sudo: 'ALL=(ALL) PASSWD:ALL'
    shell: /bin/bash

chpasswd:
  list:
    - "{admin_username}:temporary_password"
  expire: false

write_files:
  - path: /etc/ssh/sshd_config.d/00-cloud-init.conf
    content: |
      AcceptEnv K3S_*
  - path: /usr/local/bin/shutdown-node.sh
    content: |
      #/usr/bin/env sh
      (sleep 3 && shutdown now) &
    permissions: '0755'

runcmd:
  - curl -sfL -o /usr/local/bin/k3s-init.sh https://get.k3s.io
  - chmod 0755 /usr/local/bin/k3s-init.sh
  - service ssh restart
