fqdn: {hostname}
prefer_fqdn_over_hostname: true
manage_etc_hosts: true

apt:
  preserve_sources_list: true
  sources:
    docker:
      key: {docker_key_content:?}
      source: "deb [arch=arm64 signed-by=$KEY_FILE] https://download.docker.com/linux/ubuntu $RELEASE stable"

package_update: true
package_upgrade: false
packages:
  - [docker-ce, 5:20.10.22~3-0~ubuntu-focal]
  - [docker-ce-cli, 5:20.10.22~3-0~ubuntu-focal]

users:
  - name: {admin_username}
    groups:
      - adm
      - dialout
      - cdrom
      - sudo
      - audio
      - video
      - plugdev
      - games
      - users
      - input
      - netdev
      - gpio
      - i2c
      - spi
    ssh_authorized_keys:
      - {ssh_pub_key}
    sudo: 'ALL=(ALL) PASSWD:ALL'
    shell: /bin/bash

chpasswd:
  list:
    - "{admin_username}:temporary_password"
  expire: false
runcmd:
  - curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.25.4 sh -
