fqdn: {hostname}
prefer_fqdn_over_hostname: true
manage_etc_hosts: true

package_update: true
package_upgrade: false

users:
  - name: {admin_username}
    groups:
      - adm
      - dialout
      - cdrom
      - sudo
      - audio
      - video
      - plugdev
      - games
      - users
      - input
      - netdev
      - gpio
      - i2c
      - spi
    ssh_authorized_keys:
      - {ssh_pub_key}
    sudo: 'ALL=(ALL) PASSWD:ALL'
    shell: /bin/bash

chpasswd:
  list:
    - "{admin_username}:temporary_password"
  expire: false
runcmd:
  - curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.25.4 sh -
