name: Create Release

on:
  workflow_dispatch:
    inputs:
      bumpVersion:
        description: "Bump version"
        required: true
        default: patch
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch master
        run: |
          git fetch origin master:master
      - name: Bump version
        id: bump
        run: |
          new_version=`scripts/bumb_version.py $BUMP_VERSION`
          echo "::set-output name=NEW_VERSION::$new_version"
        env:
          BUMP_VERSION: ${{ inputs.bumpVersion }}
      - name: Commit changes
        run: |
          git config user.name "release"
          git commit -a -m "Prepare Release v${{steps.bump.outputs.NEW_VERSION}}"
