name: Create Release

on:
  workflow_dispatch:
    inputs:
      bumpVersion:
        description: "Bump version"
        required: true
        default: patch
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch master
        run: |
          git fetch origin master:master
      - name: Bump version
        run: |
          scripts/bumb_version.py $BUMP_VERSION
        env:
          BUMP_VERSION: ${{ inputs.bumpVersion }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: develop
          base: master
